### ISSUE TITLE
Printing and page footer

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/Jekyll-Theme#1]
The page footer obstructs part of the text when printing. As a result, printed pages are missing the information at the bottom of this page. Is there a way to:

1. Change the theme so this issue is resolved?

1. Disable the footer altogether (with a setting somewhere)?

Example:

![image](https://user-images.githubusercontent.com/1765732/73754091-d1613600-4731-11ea-9347-c13bbcdb3cc6.png)

**Comment by seesharprun** [comment]
I think we can fix this by using the ``d-print-none`` class in Bootstrap CSS.

I fixed that in commits 0622192f72c083d769183e40e7158c0d8290d35d & 6635f109d24b432d68a9f4b54256213951ca03cd

We can make a change here but it won't show up in each individual repository until they make their next change.

GitHub Pages only builds the website each time the source repository is updated. If a repository (for example AZ-203) changes, it pulls the theme content from this repository and builds the website.

**Comment by VitalyMCT** [comment]
Thanks @seesharprun! I tested this in my own repo and it works great.
